apiVersion: ols.openshift.io/v1alpha1
kind: OLSConfig
metadata:
  name: cluster
spec:
  llm:
    providers:
      - name: Google-Gemini
        type: openai
        credentialsSecretRef:
          name: credentials-openai
        url: https://generativelanguage.googleapis.com/v1beta
        models:
          - name: gemini-2.0-flash
  ols:
    introspectionEnabled: true
    defaultModel: gemini-2.0-flash
    defaultProvider: Google-Gemini



apiVersion: v1
kind: Secret
metadata:
  name: credentials-openai
  namespace: openshift-lightspeed
type: Opaque
stringData:
  apitoken: ${TOKEN}
